# Autogenerated by https://github.com/mcpeachpies/mcpeachpies-datapacks/blob/master/pronouns/.generate_teams
team add mpp_prn_any
team modify mpp_prn_any suffix ["",{"text":" [any]","color":"gray"}]
team add mpp_prn_ask
team modify mpp_prn_ask suffix ["",{"text":" [ask]","color":"gray"}]
team add mpp_prn_avoid
team modify mpp_prn_avoid suffix ["",{"text":" [avoid]","color":"gray"}]
team add mpp_prn_other
team modify mpp_prn_other suffix ["",{"text":" [other]","color":"gray"}]
team add mpp_prn_he_him
team modify mpp_prn_he_him suffix ["",{"text":" [he/him]","color":"gray"}]
team add mpp_prn_he_it
team modify mpp_prn_he_it suffix ["",{"text":" [he/it]","color":"gray"}]
team add mpp_prn_he_its
team modify mpp_prn_he_its suffix ["",{"text":" [he/its]","color":"gray"}]
team add mpp_prn_he_she
team modify mpp_prn_he_she suffix ["",{"text":" [he/she]","color":"gray"}]
team add mpp_prn_he_her
team modify mpp_prn_he_her suffix ["",{"text":" [he/her]","color":"gray"}]
team add mpp_prn_he_they
team modify mpp_prn_he_they suffix ["",{"text":" [he/they]","color":"gray"}]
team add mpp_prn_he_them
team modify mpp_prn_he_them suffix ["",{"text":" [he/them]","color":"gray"}]
team add mpp_prn_him_he
team modify mpp_prn_him_he suffix ["",{"text":" [him/he]","color":"gray"}]
team add mpp_prn_him_it
team modify mpp_prn_him_it suffix ["",{"text":" [him/it]","color":"gray"}]
team add mpp_prn_him_its
team modify mpp_prn_him_its suffix ["",{"text":" [him/its]","color":"gray"}]
team add mpp_prn_him_she
team modify mpp_prn_him_she suffix ["",{"text":" [him/she]","color":"gray"}]
team add mpp_prn_him_her
team modify mpp_prn_him_her suffix ["",{"text":" [him/her]","color":"gray"}]
team add mpp_prn_him_they
team modify mpp_prn_him_they suffix ["",{"text":" [him/they]","color":"gray"}]
team add mpp_prn_him_them
team modify mpp_prn_him_them suffix ["",{"text":" [him/them]","color":"gray"}]
team add mpp_prn_it_he
team modify mpp_prn_it_he suffix ["",{"text":" [it/he]","color":"gray"}]
team add mpp_prn_it_him
team modify mpp_prn_it_him suffix ["",{"text":" [it/him]","color":"gray"}]
team add mpp_prn_it_its
team modify mpp_prn_it_its suffix ["",{"text":" [it/its]","color":"gray"}]
team add mpp_prn_it_she
team modify mpp_prn_it_she suffix ["",{"text":" [it/she]","color":"gray"}]
team add mpp_prn_it_her
team modify mpp_prn_it_her suffix ["",{"text":" [it/her]","color":"gray"}]
team add mpp_prn_it_they
team modify mpp_prn_it_they suffix ["",{"text":" [it/they]","color":"gray"}]
team add mpp_prn_it_them
team modify mpp_prn_it_them suffix ["",{"text":" [it/them]","color":"gray"}]
team add mpp_prn_its_he
team modify mpp_prn_its_he suffix ["",{"text":" [its/he]","color":"gray"}]
team add mpp_prn_its_him
team modify mpp_prn_its_him suffix ["",{"text":" [its/him]","color":"gray"}]
team add mpp_prn_its_it
team modify mpp_prn_its_it suffix ["",{"text":" [its/it]","color":"gray"}]
team add mpp_prn_its_she
team modify mpp_prn_its_she suffix ["",{"text":" [its/she]","color":"gray"}]
team add mpp_prn_its_her
team modify mpp_prn_its_her suffix ["",{"text":" [its/her]","color":"gray"}]
team add mpp_prn_its_they
team modify mpp_prn_its_they suffix ["",{"text":" [its/they]","color":"gray"}]
team add mpp_prn_its_them
team modify mpp_prn_its_them suffix ["",{"text":" [its/them]","color":"gray"}]
team add mpp_prn_she_he
team modify mpp_prn_she_he suffix ["",{"text":" [she/he]","color":"gray"}]
team add mpp_prn_she_him
team modify mpp_prn_she_him suffix ["",{"text":" [she/him]","color":"gray"}]
team add mpp_prn_she_it
team modify mpp_prn_she_it suffix ["",{"text":" [she/it]","color":"gray"}]
team add mpp_prn_she_its
team modify mpp_prn_she_its suffix ["",{"text":" [she/its]","color":"gray"}]
team add mpp_prn_she_her
team modify mpp_prn_she_her suffix ["",{"text":" [she/her]","color":"gray"}]
team add mpp_prn_she_they
team modify mpp_prn_she_they suffix ["",{"text":" [she/they]","color":"gray"}]
team add mpp_prn_she_them
team modify mpp_prn_she_them suffix ["",{"text":" [she/them]","color":"gray"}]
team add mpp_prn_her_he
team modify mpp_prn_her_he suffix ["",{"text":" [her/he]","color":"gray"}]
team add mpp_prn_her_him
team modify mpp_prn_her_him suffix ["",{"text":" [her/him]","color":"gray"}]
team add mpp_prn_her_it
team modify mpp_prn_her_it suffix ["",{"text":" [her/it]","color":"gray"}]
team add mpp_prn_her_its
team modify mpp_prn_her_its suffix ["",{"text":" [her/its]","color":"gray"}]
team add mpp_prn_her_she
team modify mpp_prn_her_she suffix ["",{"text":" [her/she]","color":"gray"}]
team add mpp_prn_her_they
team modify mpp_prn_her_they suffix ["",{"text":" [her/they]","color":"gray"}]
team add mpp_prn_her_them
team modify mpp_prn_her_them suffix ["",{"text":" [her/them]","color":"gray"}]
team add mpp_prn_they_he
team modify mpp_prn_they_he suffix ["",{"text":" [they/he]","color":"gray"}]
team add mpp_prn_they_him
team modify mpp_prn_they_him suffix ["",{"text":" [they/him]","color":"gray"}]
team add mpp_prn_they_it
team modify mpp_prn_they_it suffix ["",{"text":" [they/it]","color":"gray"}]
team add mpp_prn_they_its
team modify mpp_prn_they_its suffix ["",{"text":" [they/its]","color":"gray"}]
team add mpp_prn_they_she
team modify mpp_prn_they_she suffix ["",{"text":" [they/she]","color":"gray"}]
team add mpp_prn_they_her
team modify mpp_prn_they_her suffix ["",{"text":" [they/her]","color":"gray"}]
team add mpp_prn_they_thm
team modify mpp_prn_they_thm suffix ["",{"text":" [they/them]","color":"gray"}]
team add mpp_prn_them_he
team modify mpp_prn_them_he suffix ["",{"text":" [them/he]","color":"gray"}]
team add mpp_prn_them_him
team modify mpp_prn_them_him suffix ["",{"text":" [them/him]","color":"gray"}]
team add mpp_prn_them_it
team modify mpp_prn_them_it suffix ["",{"text":" [them/it]","color":"gray"}]
team add mpp_prn_them_its
team modify mpp_prn_them_its suffix ["",{"text":" [them/its]","color":"gray"}]
team add mpp_prn_them_she
team modify mpp_prn_them_she suffix ["",{"text":" [them/she]","color":"gray"}]
team add mpp_prn_them_her
team modify mpp_prn_them_her suffix ["",{"text":" [them/her]","color":"gray"}]
team add mpp_prn_thm_thy
team modify mpp_prn_thm_thy suffix ["",{"text":" [them/they]","color":"gray"}]
team add mpp_prn_h_sh_thy
team modify mpp_prn_h_sh_thy suffix ["",{"text":" [he/she/they]","color":"gray"}]
team add mpp_prn_h_sh_it
team modify mpp_prn_h_sh_it suffix ["",{"text":" [he/she/it]","color":"gray"}]
team add mpp_prn_h_thy_sh
team modify mpp_prn_h_thy_sh suffix ["",{"text":" [he/they/she]","color":"gray"}]
team add mpp_prn_h_thy_it
team modify mpp_prn_h_thy_it suffix ["",{"text":" [he/they/it]","color":"gray"}]
team add mpp_prn_h_it_sh
team modify mpp_prn_h_it_sh suffix ["",{"text":" [he/it/she]","color":"gray"}]
team add mpp_prn_h_it_thy
team modify mpp_prn_h_it_thy suffix ["",{"text":" [he/it/they]","color":"gray"}]
team add mpp_prn_sh_h_thy
team modify mpp_prn_sh_h_thy suffix ["",{"text":" [she/he/they]","color":"gray"}]
team add mpp_prn_sh_h_it
team modify mpp_prn_sh_h_it suffix ["",{"text":" [she/he/it]","color":"gray"}]
team add mpp_prn_sh_thy_h
team modify mpp_prn_sh_thy_h suffix ["",{"text":" [she/they/he]","color":"gray"}]
team add mpp_prn_sh_thy_i
team modify mpp_prn_sh_thy_i suffix ["",{"text":" [she/they/it]","color":"gray"}]
team add mpp_prn_sh_it_h
team modify mpp_prn_sh_it_h suffix ["",{"text":" [she/it/he]","color":"gray"}]
team add mpp_prn_sh_t_thy
team modify mpp_prn_sh_t_thy suffix ["",{"text":" [she/it/they]","color":"gray"}]
team add mpp_prn_thy_h_sh
team modify mpp_prn_thy_h_sh suffix ["",{"text":" [they/he/she]","color":"gray"}]
team add mpp_prn_thy_h_it
team modify mpp_prn_thy_h_it suffix ["",{"text":" [they/he/it]","color":"gray"}]
team add mpp_prn_thy_sh_h
team modify mpp_prn_thy_sh_h suffix ["",{"text":" [they/she/he]","color":"gray"}]
team add mpp_prn_thy_sh_t
team modify mpp_prn_thy_sh_t suffix ["",{"text":" [they/she/it]","color":"gray"}]
team add mpp_prn_thy_t_h
team modify mpp_prn_thy_t_h suffix ["",{"text":" [they/it/he]","color":"gray"}]
team add mpp_prn_thy_t_sh
team modify mpp_prn_thy_t_sh suffix ["",{"text":" [they/it/she]","color":"gray"}]
team add mpp_prn_t_h_sh
team modify mpp_prn_t_h_sh suffix ["",{"text":" [it/he/she]","color":"gray"}]
team add mpp_prn_t_h_thy
team modify mpp_prn_t_h_thy suffix ["",{"text":" [it/he/they]","color":"gray"}]
team add mpp_prn_t_sh_h
team modify mpp_prn_t_sh_h suffix ["",{"text":" [it/she/he]","color":"gray"}]
team add mpp_prn_t_sh_thy
team modify mpp_prn_t_sh_thy suffix ["",{"text":" [it/she/they]","color":"gray"}]
team add mpp_prn_t_thy_h
team modify mpp_prn_t_thy_h suffix ["",{"text":" [it/they/he]","color":"gray"}]
team add mpp_prn_t_thy_sh
team modify mpp_prn_t_thy_sh suffix ["",{"text":" [it/they/she]","color":"gray"}]